# BASIC CALULATOR PROGRAM
NUM1 = FLOAT(INPUT("ENTER THE FIRST NYMBER: "))
NUM2 = FLOAT(INPUT("ENTER THE SECOND NUMBER: "))

OPERATION = INPUT ("CHOSE AN OPERATION (+, -, *, /): ")
#PERFORM THE OPERATION AND PRINT THE RESULT
IF OPERATION == '+':
    RESULT = NUM1+NUM2
    PRINT(F"{NUM1} + {NUM2} = {RESULT}")
ELIF OPERATION == '-':
    RESULT = NUM1 -NUM2
    PRINT(F"{NUM1} -{NUM2} = {RESULT}")
ELIF OPERATION == '*':
    RESULT = NUM1*NUM2
    PRINT(F"{NUM1} * {NUM2} = {RESULT}")
ELIF OPERATION == '/':
    IF NUM2 != 0:
        RESULT = NUM1 / NUM2
        PRINT (F"{NUM1} / {NUM2} = {RESULT}")
    ELSE:
        PRINT("ERROR: DIVISION BY ZERO IS NOT ALLOWED.")
ELSE: 
    PRINT("INVALID OPERATION. PLEASE CHOOSE +, -, *, OR /.")
    